# set the value of k for the kNN metric
number_of_neighbours: 5

# list of tasks
tasks:
  - "21styear"
  - "bigbang"
  - "black"
  - "bronx"
  - "forgot"
  - "friends"
  - "himym"
  - "lucy"
  - "merlin"
  - "milkywayoriginal"
  - "milkywaysynonyms"
  - "milkywayvodka"
  - "notthefallintact"
  - "notthefalllongscram"
  - "notthefallshortscram"
  - "pieman"
  - "piemanpni"
  - "prettymouth"
  - "santa"
#  - "schema"
  - "seinfeld"
  - "shame"
  - "shapesphysical"
  - "shapessocial"
  - "sherlock"
  - "slumlordreach"
  - "tunnel"
  - "upintheair"
  - "vinny"

# subtasks of "schema" task
schema_subtasks:
  - "bigbang"
  - "friends"
  - "himym"
  - "santa"
  - "seinfeld"
  - "shame"
  - "upintheair"
  - "vinny"

# variants of "notthefall" task
notthefall_variants:
  - "notthefalllongscram"
  - "notthefallshortscram"