rule all_llm_llm_alignment:
    input:
        [
            f"results/alignment_scores/dataset-{pair['dataset']}_model-{pair['model_1']}-{pair['stimuli_type_1']}_model-{pair['model_2']}-{pair['stimuli_type_2']}_{pair['similarity_type']}-alignment_score_{pair['number_of_neighbours']}NN.parquet"
            for pair in LLM_LLM_PAIRINGS
        ],
        [
            f"results/alignment_heatmaps/dataset-{pair['dataset']}_{pair['similarity_type']}-alignment_score_{pair['number_of_neighbours']}NN.png"
            for pair in HEATMAP_PAIRINGS
        ]

rule compute_llm_llm_alignment_score:
    input:
        llm_nearest_neighbours_1="results/{stimuli_type_1}_models/{dataset}/{similarity_type}_nearest_neighbours/{model_1}_{similarity_type}_nearest_neighbours_{number_of_neighbours}NN.parquet",
        llm_nearest_neighbours_2="results/{stimuli_type_2}_models/{dataset}/{similarity_type}_nearest_neighbours/{model_2}_{similarity_type}_nearest_neighbours_{number_of_neighbours}NN.parquet"
    output:
        llm_llm_alignment_score="results/alignment_scores/dataset-{dataset}_model-{model_1}-{stimuli_type_1}_model-{model_2}-{stimuli_type_2}_{similarity_type}-alignment_score_{number_of_neighbours}NN.parquet"
    params:
        number_of_neighbours=lambda wc: wc.number_of_neighbours
    conda:
        "envs/compute_llm_llm_alignment_score_environment.yaml"
    shell:
        r"""
            python3 workflow/llm_llm_alignment/scripts/compute_llm_llm_alignment_score.py \
                --number_of_neighbours {params.number_of_neighbours} \
                --llm_nearest_neighbours_1 {input.llm_nearest_neighbours_1:q} \
                --llm_nearest_neighbours_2 {input.llm_nearest_neighbours_2:q} \
                --alignment_score {output.llm_llm_alignment_score:q}
        """

rule plot_alignment_heatmap:
    input:
        llm_brain_alignment_scores=lambda wc: [
            f"results/alignment_scores/dataset-{wc.dataset}_model-{pair['model']}-{pair['stimuli_type']}_brain_{wc.similarity_type}-alignment_score_{wc.number_of_neighbours}NN.parquet"
            for pair in PAIRINGS
            if pair["dataset"] == wc.dataset
            and pair["similarity_type"] == wc.similarity_type
            and str(pair["number_of_neighbours"]) == str(wc.number_of_neighbours)
        ],
        llm_llm_alignment_scores=lambda wc: [
            f"results/alignment_scores/dataset-{wc.dataset}_model-{pair['model_1']}-{pair['stimuli_type_1']}_model-{pair['model_2']}-{pair['stimuli_type_2']}_{wc.similarity_type}-alignment_score_{wc.number_of_neighbours}NN.parquet"
            for pair in LLM_LLM_PAIRINGS
            if pair["dataset"] == wc.dataset
            and pair["similarity_type"] == wc.similarity_type
            and str(pair["number_of_neighbours"]) == str(wc.number_of_neighbours)
        ]
    output:
        heatmap="results/alignment_heatmaps/dataset-{dataset}_{similarity_type}-alignment_score_{number_of_neighbours}NN.png"
    conda:
        "envs/plot_alignment_heatmap_environment.yaml"
    shell:
        r"""
            python3 workflow/llm_llm_alignment/scripts/plot_alignment_heatmap.py \
                --llm_brain_alignment_scores {input.llm_brain_alignment_scores:q} \
                --llm_llm_alignment_scores {input.llm_llm_alignment_scores:q} \
                --heatmap {output.heatmap:q}
        """