DATASETS = list(config["datasets"])
SIMILARITY_TYPES = list(config["similarity_metrics"])
NUMBER_OF_NEIGHBOURS = list(config["number_of_neighbours"])

rule all_isc_nearest_neighbours:
    input:
        expand(
            "results/mind/{dataset}/{similarity_type}_nearest_neighbours/isc_{similarity_type}_nearest_neighbours_{number_of_neighbours}NN.parquet",
            dataset=DATASETS,
            similarity_type=SIMILARITY_TYPES,
            number_of_neighbours=NUMBER_OF_NEIGHBOURS
        )

rule create_isc_dataframe:
    input:
        isc_npys=lambda wc: [
            f"results/mind/{wc.dataset}/isc/task-{task}_isc_mean.npy"
            for task in config[wc.dataset]["tasks"] if task not in config[wc.dataset]["problematic_subtasks"]
        ]
    output:
        "results/mind/{dataset}/embedding_isc_dataframe.parquet"
    conda:
        "envs/create_isc_dataframe_environment.yaml"
    shell:
        r"""
            python3 workflow/isc_nearest_neighbours/scripts/create_isc_dataframe.py \
                --isc_npys {input:q} \
                --embedding_isc_dataframe {output:q}
        """

rule compute_isc_similarity:
    input:
        embedding_isc_dataframe="results/mind/{dataset}/embedding_isc_dataframe.parquet"
    output:
        isc_cosine_similarity_dataframe="results/mind/{dataset}/cosine_similarity/isc_cosine_similarity.parquet",
        isc_pearson_similarity_dataframe="results/mind/{dataset}/pearson_similarity/isc_pearson_similarity.parquet"
    conda:
        "envs/compute_isc_similarity_environment.yaml"
    shell:
        r"""
            python3 workflow/isc_nearest_neighbours/scripts/compute_isc_similarity.py \
                --embedding_isc_dataframe {input.embedding_isc_dataframe:q} \
                --isc_cosine_similarity_dataframe {output.isc_cosine_similarity_dataframe:q} \
                --isc_pearson_similarity_dataframe {output.isc_pearson_similarity_dataframe:q}
        """

rule compute_isc_nearest_neighbours:
    input:
        isc_cosine_similarity_dataframe="results/mind/{dataset}/cosine_similarity/isc_cosine_similarity.parquet",
        isc_pearson_similarity_dataframe="results/mind/{dataset}/pearson_similarity/isc_pearson_similarity.parquet"
    output:
        isc_cosine_nearest_neighbours="results/mind/{dataset}/cosine_nearest_neighbours/isc_cosine_nearest_neighbours_{number_of_neighbours}NN.parquet",
        isc_pearson_nearest_neighbours="results/mind/{dataset}/pearson_nearest_neighbours/isc_pearson_nearest_neighbours_{number_of_neighbours}NN.parquet"
    params:
        number_of_neighbours=lambda wc: wc.number_of_neighbours
    conda:
        "envs/compute_isc_nearest_neighbours_environment.yaml"
    shell:
        r"""
            python3 workflow/isc_nearest_neighbours/scripts/compute_isc_nearest_neighbours.py \
                --isc_cosine_similarity_dataframe {input.isc_cosine_similarity_dataframe:q} \
                --isc_pearson_similarity_dataframe {input.isc_pearson_similarity_dataframe:q} \
                --isc_cosine_nearest_neighbours {output.isc_cosine_nearest_neighbours:q} \
                --isc_pearson_nearest_neighbours {output.isc_pearson_nearest_neighbours:q} \
                --number_of_neighbours {params.number_of_neighbours}
        """