DATASETS = list(config["datasets"])
MODEL_KEYS = list(config["models"].keys())
SIMILARITY_TYPES = list(config["similarity_metrics"])
NUMBER_OF_RELABELLINGS = range(config["number_of_relabellings"])

def dataset_neighbour_pairs():
    pairs = []

    for dataset in DATASETS:
        nn = config[dataset]["number_of_neighbours"]

        # allow both old scalar syntax and new list syntax
        if isinstance(nn, int):
            nn = [nn]

        for number_of_neighbours in nn:
            pairs.append(
                {
                    "dataset": dataset,
                    "number_of_neighbours": number_of_neighbours,
                }
            )

    return pairs

DATASET_NN_PAIRS = dataset_neighbour_pairs()

rule all_llm_mind_alignment:
    input:
        [
            f"results/alignment_score/{pair['dataset']}/{similarity_type}_alignment_scores/{model}_brain_{similarity_type}_alignment_score_{pair['number_of_neighbours']}NN.parquet"
            for pair in DATASET_NN_PAIRS
            for similarity_type in SIMILARITY_TYPES
            for model in MODEL_KEYS
        ],
        [
            f"results/alignment_summary/{pair['dataset']}/parquet_summary/{similarity_type}_alignment_summary_{pair['number_of_neighbours']}NN_all_models.parquet"
            for pair in DATASET_NN_PAIRS
            for similarity_type in SIMILARITY_TYPES
        ],
        [
            f"results/alignment_summary/{pair['dataset']}/tsv_summary/{similarity_type}_alignment_summary_{pair['number_of_neighbours']}NN_all_models.tsv"
            for pair in DATASET_NN_PAIRS
            for similarity_type in SIMILARITY_TYPES
        ]

rule compute_llm_mind_alignment_score:
    input:
        isc_nearest_neighbours="results/mind/{dataset}/isc_{similarity_type}_nearest_neighbours_{number_of_neighbours}NN.parquet",
        llm_nearest_neighnours="results/llm/{dataset}/{similarity_type}_nearest_neighbours/{model}_{similarity_type}_nearest_neighbours_{number_of_neighbours}NN.parquet"
    output:
        llm_brain_alignment_score="results/alignment_score/{dataset}/{similarity_type}_alignment_scores/{model}_brain_{similarity_type}_alignment_score_{number_of_neighbours}NN.parquet"
    params:
        number_of_neighbours=lambda wc: wc.number_of_neighbours,
        model="{model}"
    conda:
        "envs/compute_llm_mind_alignment_score_environment.yaml"
    shell:
        r"""
            python3 workflow/llm_mind_alignment/scripts/compute_llm_mind_alignment_score.py \
                --number_of_neighbours {params.number_of_neighbours} \
                --model {params.model:q} \
                --nearest_neighbours_1 {input.isc_nearest_neighbours:q} \
                --nearest_neighbours_2 {input.llm_nearest_neighnours:q} \
                --alignment_score {output.llm_brain_alignment_score:q}
        """

rule compute_relabelled_llm_mind_alignment_score:
    input:
        isc_nearest_neighbours="results/mind/{dataset}/isc_{similarity_type}_nearest_neighbours_{number_of_neighbours}NN.parquet",
        relabelled_llm_nearest_neighbours="results/llm/{dataset}/relabelled_nearest_neighbours/relabelled_{model}_{similarity_type}_nearest_neighbours_{number_of_neighbours}NN.parquet"
    output:
        relabelled_alignment_score="results/alignment_score/{dataset}/{similarity_type}_alignment_scores/{model}_brain_relabelled_{similarity_type}_alignment_score_{number_of_neighbours}NN.parquet"
    params:
        number_of_neighbours=lambda wc: wc.number_of_neighbours,
        model="{model}"
    conda:
        "envs/compute_relabelled_llm_mind_alignment_score_environment.yaml"
    shell:
        r"""
            python3 workflow/llm_mind_alignment/scripts/compute_relabelled_llm_mind_alignment_score.py \
                --number_of_neighbours {params.number_of_neighbours} \
                --model {params.model:q} \
                --relabelled_llm_nearest_neighbours {input.relabelled_llm_nearest_neighbours:q} \
                --isc_nearest_neighbours {input.isc_nearest_neighbours:q} \
                --relabelled_alignment_score {output.relabelled_alignment_score:q}
        """

rule aggregate_all_alignment_scores:
    input:
        observed_alignment_scores=lambda wc: [
            f"results/alignment_score/{wc.dataset}/{wc.similarity_type}_alignment_scores/{model}_brain_{wc.similarity_type}_alignment_score_{wc.number_of_neighbours}NN.parquet"
            for model in MODEL_KEYS
        ],
        relabelled_alignment_scores=lambda wc: [
            f"results/alignment_score/{wc.dataset}/{wc.similarity_type}_alignment_scores/{model}_brain_relabelled_{wc.similarity_type}_alignment_score_{wc.number_of_neighbours}NN.parquet"
            for model in MODEL_KEYS
        ]
    output:
        summary="results/alignment_summary/{dataset}/parquet_summary/{similarity_type}_alignment_summary_{number_of_neighbours}NN_all_models.parquet",
        tsv="results/alignment_summary/{dataset}/tsv_summary/{similarity_type}_alignment_summary_{number_of_neighbours}NN_all_models.tsv"
    params:
        models=MODEL_KEYS,
        number_of_neighbours=lambda wc: wc.number_of_neighbours,
        number_of_relabelings=config["number_of_relabellings"]
    conda:
        "envs/aggregate_all_alignment_scores_environment.yaml"
    shell:
        r"""
            python3 workflow/llm_mind_alignment/scripts/aggregate_all_alignment_scores.py \
                --observed_alignment_scores {input.observed_alignment_scores:q} \
                --relabelled_alignment_scores {input.relabelled_alignment_scores:q} \
                --summary {output.summary:q} \
                --tsv {output.tsv:q} \
                --models {params.models:q} \
                --number_of_neighbours {params.number_of_neighbours} \
                --number_of_relabelings {params.number_of_relabelings}
        """