# number of nearest neighbours to compute for each stimulus and model
number_of_neighbours: [3, 5]

# configuration for relabelled similarity computation
number_of_relabellings: 10000
random_seed: 37

# models
models:
  bloom_560m:
    name: "BLOOMZ-560M"
    hf_name: "bigscience/bloomz-560m"
    quantization_method: null
  bloom_1b1:
    name: "BLOOMZ-1.1B"
    hf_name: "bigscience/bloomz-1b1"
    quantization_method: null
  bloom_1b7:
    name: "BLOOMZ-1.7B"
    hf_name: "bigscience/bloomz-1b7"
    quantization_method: null
  bloom_3b:
    name: "BLOOMZ-3B"
    hf_name: "bigscience/bloomz-3b"
    quantization_method: null
  bloom_7b1:
    name: "BLOOMZ-7.1B"
    hf_name: "bigscience/bloomz-7b1"
    quantization_method: null
  openllama_3b:
    name: "OpenLLaMA-3B"
    hf_name: "openlm-research/open_llama_3b"
    quantization_method: null
  openllama_7b:
    name: "OpenLLaMA-7B"
    hf_name: "openlm-research/open_llama_7b"
    quantization_method: null
  openllama_13b:
    name: "OpenLLaMA-13B"
    hf_name: "openlm-research/open_llama_13b"
    quantization_method: "8bit"

# similarity metrics
similarity_metrics:
 - "cosine"
 - "pearson"

# datasets
datasets:
  - "narratives"
#  - "caption_scene"

##### NARRATIVES DATASET #####
# dataset configuration
narratives:
  bold_pattern: "resources/datasets/narratives_dataset/derivatives/afni-smooth/sub-{subject}/func/sub-{subject}_task-{task}{run_tag}_space-{space}_res-{resolution}_desc-{descriptor}_bold.nii.gz"
  scans_to_be_excluded: "resources/datasets/narratives_dataset/scan_exclude.json"
  excluded_scans_for_task: "resources/datasets/narratives_dataset/excluded_scans_for_task.json"
  processing_output_dir: "results/mind/narratives"
  stimuli: "results/llm/narratives/manifests/stimuli.tsv"
  subjects: 345
  tasks:
    - "21styear"
    - "bigbang"
    - "black"
    - "bronx"
    - "forgot"
    - "friends"
    - "himym"
    - "lucy"
    - "merlin"
#    - "milkyway"
    - "milkywayoriginal"
    - "milkywaysynonyms"
    - "milkywayvodka"
    - "notthefallintact"
    - "notthefalllongscram"
    - "notthefallshortscram"
    - "pieman"
    - "piemanpni"
    - "prettymouth"
    - "santa"
#    - "schema"
    - "seinfeld"
    - "shame"
    - "shapesphysical"
    - "shapessocial"
    - "sherlock"
    - "slumlordreach"
    - "tunnel"
    - "upintheair"
    - "vinny"
  run_tags:
    - ""
    - "_run-1"
    - "_run-2"
  spaces:
    - "MNI152NLin2009cAsym"
  resolutions:
    - "native"
  descriptors:
    - "clean"
  subtasks:
  # subtasks of "schema" task
  schema_subtasks:
    - "bigbang"
    - "friends"
    - "himym"
    - "santa"
    - "seinfeld"
    - "shame"
    - "upintheair"
    - "vinny"
  # variants of "notthefall" task
  notthefall_variants:
    - "notthefalllongscram"
    - "notthefallshortscram"
  problematic_subtasks:
    - "bigbang"
    - "friends"
    - "himym"
    - "santa"
    - "seinfeld"
    - "shame"
    - "upintheair"
    - "vinny"
    - "notthefalllongscram"
    - "notthefallshortscram"

##### CAPTION-SCENE DATASET #####
caption_scene:
  bold_glob: "resources/datasets/caption_scene_dataset/V1/derivatives/pp_data/sub-*/func/sub-*_ses-*_task-CSD_run-*.nii.gz"
  scans_to_be_excluded: "resources/datasets/caption_scene_dataset/scan_exclude.json"
  excluded_scans_for_task: "resources/datasets/caption_scene_dataset/excluded_scans_for_task.json"
  processing_output_dir: "results/mind/caption_scene"
  stimuli: "results/llm/caption_scene/manifests/stimuli.tsv"
  subjects: 8
  tr: 2.0
  event_duration_s: 12.0
  onset_shift_s: 0.0
  run_table_encoding: "gbk"

# atlas configuration
atlas:
  atlas_dir: "resources/atlases"
  n_rois: 200
  yeo_networks: 7