channels:
  - conda-forge
  - main
  - nodefaults
dependencies:
  - python=3.12
  - pandas
  - pyarrow
  - pytorch
  - torchvision
  - torchaudio
  - timm
  - tqdm
  - datasets
  - scikit-learn
  - pillow
  - transformers
  - accelerate
  - sentencepiece
  - protobuf
  - bitsandbytes