SPEARMAN_PAIRINGS = [
    {
        "dataset": dataset,
        "stimuli_type": stimuli_type,
        "model": model,
        "similarity_type": similarity_type,
    }
    for dataset in DATASETS
    for stimuli_type in config[dataset]["stimuli_dir"]
    for model in MODEL_KEYS
    if config["models"][model]["modality"] in [stimuli_type, "multimodal"]
    for similarity_type in SIMILARITY_TYPES
]

rule all_spearman_alignment:
    input:
        [
            f"results/spearman_alignment_scores/dataset-{pair['dataset']}_model-{pair['model']}-{pair['stimuli_type']}_brain_empirical_{pair['similarity_type']}-spearman_alignment_model_level.p_value.tsv"
            for pair in SPEARMAN_PAIRINGS
        ],
        [
            f"results/spearman_alignment_scores/dataset-{pair['dataset']}_model-{pair['model']}-{pair['stimuli_type']}_brain_empirical_{pair['similarity_type']}-spearman_alignment_concept_level.p_value.tsv"
            for pair in SPEARMAN_PAIRINGS
        ],
        "results/all_spearman_alignment_scores.tsv"

rule compute_spearman_alignmentwith_empirical_p_value:
    input:
        brain_embeddings="results/mind/{dataset}/isc_dataframe.parquet",
        model_embeddings="results/{stimuli_type}_models/{dataset}/embeddings/{model}_embeddings.parquet"
    output:
        model_level="results/spearman_alignment_scores/dataset-{dataset}_model-{model}-{stimuli_type}_brain_empirical_{similarity_type}-spearman_alignment_model_level.p_value.tsv",
        concept_level="results/spearman_alignment_scores/dataset-{dataset}_model-{model}-{stimuli_type}_brain_empirical_{similarity_type}-spearman_alignment_concept_level.p_value.tsv"
    params:
        number_of_relabellings=NUMBER_OF_RELABELLINGS,
        random_seed=RANDOM_SEED
    conda:
        "envs/spearman_alignment_environment.yaml"
    shell:
        r"""
            python3 workflow/spearman_alignment/scripts/compute_spearman_alignment_with_empirical_p_value.py \
                --brain_embeddings {input.brain_embeddings:q} \
                --model_embeddings {input.model_embeddings:q} \
                --model_level_output {output.model_level:q} \
                --concept_level_output {output.concept_level:q} \
                --dataset {wildcards.dataset:q} \
                --model {wildcards.model:q} \
                --stimuli_type {wildcards.stimuli_type:q} \
                --similarity_type {wildcards.similarity_type:q} \
                --number_of_relabellings {params.number_of_relabellings} \
                --random_seed {params.random_seed}
        """

rule aggregate_all_spearman_alignment_scores:
    input:
        model_level_scores=[
            f"results/spearman_alignment_scores/dataset-{pair['dataset']}_model-{pair['model']}-{pair['stimuli_type']}_brain_empirical_{pair['similarity_type']}-spearman_alignment_model_level.p_value.tsv"
            for pair in SPEARMAN_PAIRINGS
        ]
    output:
        all_spearman_alignment_scores_tsv="results/all_spearman_alignment_scores.tsv"
    conda:
        "envs/spearman_alignment_environment.yaml"
    shell:
        r"""
            python3 workflow/spearman_alignment/scripts/aggregate_all_spearman_outputs.py \
                --model_level_scores {input.model_level_scores:q} \
                --all_spearman_alignment_scores_tsv {output.all_spearman_alignment_scores_tsv:q}
        """