from pathlib import Path

DATASETS = list(config["datasets"])
MODEL_KEYS = list(config["models"].keys())
SIMILARITY_TYPES = list(config["similarity_metrics"])
NUMBER_OF_RELABELLINGS = config["number_of_relabellings"]

def pairings():
    pairs = []

    for dataset in DATASETS:
        nn = config[dataset]["number_of_neighbours"]

        # allow both old scalar syntax and new list syntax
        if isinstance(nn, int):
            nn = [nn]

        for number_of_neighbours in nn:
            for stimuli_type in list(config[dataset]["stimuli_dir"].keys()):
                for model in MODEL_KEYS:
                    if config["models"][model]["modality"] in [stimuli_type, "multimodal"]:
                        pairs.append(
                            {
                                "dataset": dataset,
                                "number_of_neighbours": number_of_neighbours,
                                "stimuli_type": stimuli_type,
                                "model": model
                            }
                        )

    return pairs

PAIRINGS = pairings()

rule all_llm_nearest_neighbours:
    input:
        [
            f"results/{pair['stimuli_type']}_models/{pair['dataset']}/{similarity_type}_nearest_neighbours/{pair['model']}_{similarity_type}_nearest_neighbours_{pair['number_of_neighbours']}NN.parquet"
            for pair in PAIRINGS
            for similarity_type in SIMILARITY_TYPES
        ],
        [
            f"results/{pair['stimuli_type']}_models/{pair['dataset']}/relabelled_nearest_neighbours/relabelled_{pair['model']}_{similarity_type}_nearest_neighbours_{pair['number_of_neighbours']}NN.parquet"
            for pair in PAIRINGS
            for similarity_type in SIMILARITY_TYPES
        ]

rule download_pretrained_llm:
    output:
        model_dir=directory("resources/models/{model}")
    params:
        hf_name=lambda wc: config["models"][wc.model]["hf_name"]
    conda:
        "envs/download_pretrained_llm_environment.yaml"
    shell:
        r"""
            python3 workflow/llm_nearest_neighbours/scripts/download_pretrained_llm.py {params.hf_name:q} {output.model_dir:q}
        """

rule get_embeddings:
    input:
        stimuli_transcripts_done=lambda wc: config[wc.dataset]["stimuli_ready"],
        stimuli_dir=lambda wc: config[wc.dataset]["stimuli_dir"][wc.stimuli_type],
        excluded_stimuli=lambda wc: config[wc.dataset]["excluded_stimuli"],
        model="resources/models/{model}"
    output:
        "results/{stimuli_type}_models/{dataset}/embeddings/{model}_embeddings.parquet"
    resources:
        gpu=1
    params:
        modality=lambda wc: config["models"][wc.model]["modality"],
        quantization_arg=lambda wc: (
            "" if config["models"][wc.model]["quantization_method"] is None
            else f"--quantization_method {config['models'][wc.model]['quantization_method']}"
        )
    conda:
        "envs/get_embeddings_environment.yaml"
    shell:
        r"""
            python3 workflow/llm_nearest_neighbours/scripts/get_embeddings.py \
                --stimuli_dir {input.stimuli_dir:q} \
                --output {output:q} \
                --model_path {input.model:q} \
                --modality {params.modality:q} \
                {params.quantization_arg} \
                --excluded_stimuli {input.excluded_stimuli:q}
        """

rule compute_llm_similarity:
    input:
        embedding_dataframe="results/{stimuli_type}_models/{dataset}/embeddings/{model}_embeddings.parquet"
    output:
        cosine_similarity_dataframe="results/{stimuli_type}_models/{dataset}/cosine_similarity/{model}_cosine_similarity.parquet",
        pearson_similarity_dataframe="results/{stimuli_type}_models/{dataset}/pearson_similarity/{model}_pearson_similarity.parquet"
    conda:
        "envs/compute_llm_similarity_environment.yaml"
    shell:
        r"""
            python3 workflow/llm_nearest_neighbours/scripts/compute_llm_similarity.py \
                --embedding_dataframe {input.embedding_dataframe:q} \
                --cosine_similarity_dataframe {output.cosine_similarity_dataframe:q} \
                --pearson_similarity_dataframe {output.pearson_similarity_dataframe:q}
        """

rule compute_llm_nearest_neighbours:
    input:
        similarity_dataframe="results/{stimuli_type}_models/{dataset}/{similarity_type}_similarity/{model}_{similarity_type}_similarity.parquet"
    output:
        nearest_neighbours="results/{stimuli_type}_models/{dataset}/{similarity_type}_nearest_neighbours/{model}_{similarity_type}_nearest_neighbours_{number_of_neighbours}NN.parquet"
    params:
        number_of_neighbours=lambda wc: wc.number_of_neighbours
    conda:
        "envs/compute_llm_nearest_neighbours_environment.yaml"
    shell:
        r"""
            python3 workflow/llm_nearest_neighbours/scripts/compute_llm_nearest_neighbours.py \
                --number_of_neighbours {params.number_of_neighbours:q} \
                --similarity_dataframe {input.similarity_dataframe:q} \
                --nearest_neighbours {output.nearest_neighbours:q}
        """

rule relabel_llm_similarity_and_compute_relabelled_llm_nearest_neighbours:
    input:
        similarity_dataframe="results/{stimuli_type}_models/{dataset}/{similarity_type}_similarity/{model}_{similarity_type}_similarity.parquet"
    output:
        relabelled_nearest_neighbours="results/{stimuli_type}_models/{dataset}/relabelled_nearest_neighbours/relabelled_{model}_{similarity_type}_nearest_neighbours_{number_of_neighbours}NN.parquet"
    params:
        number_of_neighbours=lambda wc: wc.number_of_neighbours,
        number_of_relabellings=NUMBER_OF_RELABELLINGS,
        random_seed=config["random_seed"]
    conda:
        "envs/relabel_llm_similarity_and_compute_relabelled_llm_nearest_neighbours_environment.yaml"
    shell:
        r"""
            python3 workflow/llm_nearest_neighbours/scripts/relabel_llm_similarity_and_compute_relabelled_llm_nearest_neighbours.py \
                --similarity_dataframe {input.similarity_dataframe:q} \
                --relabelled_nearest_neighbours {output.relabelled_nearest_neighbours:q} \
                --number_of_neighbours {params.number_of_neighbours} \
                --number_of_relabellings {params.number_of_relabellings} \
                --random_seed {params.random_seed} > {output}
        """